#!/bin/bash

# Define color codes (change these for your preference)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
RESET='\033[0m'  # Reset color

# Title with ASCII art and emoji
echo -e "
  ____   __   _  _  _ 
 / ___\ / /  | || | || |
|  _  |\ \  | || || || |
| |_| | \_\ | || || || |
 \____/  \___/|_||_||_|

${BOLD}** GitLeaks Scanner **${RESET} 🕵️‍♂️🔍
"

# Download and execute gitleaks_on_clone script
echo -e "${BOLD}Downloading and executing gitleaks_on_clone script...${RESET}"
wget -qO- https://raw.githubusercontent.com/ruslanlap/pre-commit-auto-script/main/gitleaks_on_clone | bash -

# Check if gitleaks_on_clone script execution was successful
if [ $? -eq 0 ]; then
  echo -e "${GREEN}✅ ** Gitleaks scan completed successfully!${RESET}"
else
  echo -e "${RED}❌ ** ERROR: Failed to execute gitleaks_on_clone script.${RESET}"
  exit 1
fi

echo -e "${GREEN}** Task completed. **${RESET} 🎉"

